### ISSUE TITLE
The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions

### ISSUE THREAD

**Issue by cornelcroi** [aws-solutions/secure-media-delivery-at-the-edge-on-aws#7]
**Describe the bug**
The code uses `custom_resources.AwsCustomResource`which uses an old runtime for the Lambda function.

**To Reproduce**
Deploy the application using CDK or CFN template.

**Expected behavior**
Impossible to deploy the application as nodejs12 runtime is not supported anymore.

**Please complete the following information about the solution:**
An issue on CDK is open: https://github.com/aws/aws-cdk/issues/23682, not solved yet.

- [v1.1.3] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository? No.
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by kaizencc** [comment]
The current aws-cdk-lib custom resource uses Node 14. Your solution is to update aws-cdk-lib to the latest version.

**Comment by cassneal** [comment]
We are updating this today. Will comment here once we have released.

**Comment by cassneal** [comment]
Secure Media Delivery at the Edge on AWS 1.1.4 has been released and includes the update to aws-cdk-lib to the latest version.
